### ISSUE TITLE
Teams Missing in Outlook

### ISSUE THREAD

**Issue by rucheat** [pbowden-msft/MobileConfigs#3]
Hey,

Don't know this is the correct place for this question but I am not able to install/add Teams plugin in Outlook MAC application.

I used your profile and tried but not working.

I am using latest build downloaded from the AppStore.

Is there a way you can help me or point me to any solution if any?

Thanks

**Comment by pbowden-msft** [comment]
Hey @rucheat 

There can be several reasons why the Teams icon isn't showing up. If you want to send me an email (pbowden@microsoft.com) I can give you a tool that will help troubleshoot it.

Thanks, Paul.
